import pathlib

import pytest

from py_module_parser import parse_from_file

test_data = pathlib.Path(__file__).parents[0] / "test_data"
params = [
    (
        test_data / "gino_orm_.py",
        [
            {
                "alias": "g",
                "lineno_end": 1,
                "lineno_start": 1,
                "name": "gino",
                "node_type": "import",
            },
            {
                "imports": [
                    {
                        "alias": None,
                        "lineno_end": 2,
                        "lineno_start": 2,
                        "name": "Gino",
                        "node_type": "import",
                    }
                ],
                "lineno_end": 2,
                "lineno_start": 2,
                "module": "gino",
                "node_type": "from_import",
            },
            {
                "default": {
                    "args": [],
                    "func_name": "Gino",
                    "kwargs": {},
                    "lineno_end": 4,
                    "lineno_start": 4,
                    "node_type": "func_call",
                },
                "lineno_end": 4,
                "lineno_start": 4,
                "name": "db",
                "node_type": "variable",
                "properties": {},
                "type_annotation": None,
            },
            {
                "attrs": [
                    {
                        "default": "users",
                        "lineno_end": 8,
                        "lineno_start": 8,
                        "name": "__tablename__",
                        "node_type": "variable",
                        "properties": {},
                        "type_annotation": "str",
                    },
                    {
                        "default": {
                            "args": [
                                {
                                    "args": [],
                                    "func_name": "db.Integer",
                                    "kwargs": {},
                                    "lineno_end": 10,
                                    "lineno_start": 10,
                                    "node_type": "func_call",
                                }
                            ],
                            "func_name": "db.Column",
                            "kwargs": {"autoincrement": True, "primary_key": True},
                            "lineno_end": 10,
                            "lineno_start": 10,
                            "node_type": "func_call",
                        },
                        "lineno_end": 10,
                        "lineno_start": 10,
                        "name": "id",
                        "node_type": "variable",
                        "properties": {},
                        "type_annotation": None,
                    },
                    {
                        "default": {
                            "args": [
                                {
                                    "args": [],
                                    "func_name": "db.String",
                                    "kwargs": {},
                                    "lineno_end": 11,
                                    "lineno_start": 11,
                                    "node_type": "func_call",
                                }
                            ],
                            "func_name": "db.Column",
                            "kwargs": {},
                            "lineno_end": 11,
                            "lineno_start": 11,
                            "node_type": "func_call",
                        },
                        "lineno_end": 11,
                        "lineno_start": 11,
                        "name": "db",
                        "node_type": "variable",
                        "properties": {},
                        "type_annotation": None,
                    },
                    {
                        "default": {
                            "args": [
                                {
                                    "args": [],
                                    "func_name": "db.TIMESTAMP",
                                    "kwargs": {},
                                    "lineno_end": 12,
                                    "lineno_start": 12,
                                    "node_type": "func_call",
                                }
                            ],
                            "func_name": "db.Column",
                            "kwargs": {},
                            "lineno_end": 12,
                            "lineno_start": 12,
                            "node_type": "func_call",
                        },
                        "lineno_end": 12,
                        "lineno_start": 12,
                        "name": "created_at",
                        "node_type": "variable",
                        "properties": {},
                        "type_annotation": None,
                    },
                    {
                        "default": {
                            "args": [
                                {
                                    "args": [],
                                    "func_name": "db.TIMESTAMP",
                                    "kwargs": {},
                                    "lineno_end": 13,
                                    "lineno_start": 13,
                                    "node_type": "func_call",
                                }
                            ],
                            "func_name": "db.Column",
                            "kwargs": {},
                            "lineno_end": 13,
                            "lineno_start": 13,
                            "node_type": "func_call",
                        },
                        "lineno_end": 13,
                        "lineno_start": 13,
                        "name": "updated_at",
                        "node_type": "variable",
                        "properties": {},
                        "type_annotation": None,
                    },
                    {
                        "default": {
                            "args": [
                                {
                                    "args": [],
                                    "func_name": "db.Integer",
                                    "kwargs": {},
                                    "lineno_end": 14,
                                    "lineno_start": 14,
                                    "node_type": "func_call",
                                }
                            ],
                            "func_name": "db.Column",
                            "kwargs": {},
                            "lineno_end": 14,
                            "lineno_start": 14,
                            "node_type": "func_call",
                        },
                        "lineno_end": 14,
                        "lineno_start": 14,
                        "name": "country_code",
                        "node_type": "variable",
                        "properties": {},
                        "type_annotation": None,
                    },
                    {
                        "default": {
                            "args": [
                                {
                                    "args": [],
                                    "func_name": "db.Integer",
                                    "kwargs": {},
                                    "lineno_end": 15,
                                    "lineno_start": 15,
                                    "node_type": "func_call",
                                }
                            ],
                            "func_name": "db.Column",
                            "kwargs": {},
                            "lineno_end": 15,
                            "lineno_start": 15,
                            "node_type": "func_call",
                        },
                        "lineno_end": 15,
                        "lineno_start": 15,
                        "name": "default_language",
                        "node_type": "variable",
                        "properties": {},
                        "type_annotation": None,
                    },
                ],
                "lineno_end": 15,
                "lineno_start": 7,
                "name": "Users",
                "node_type": "class",
                "parents": ["db.Model"],
            },
        ],
    ),
    (
        test_data / "dataclass_.py",
        [
            {
                "alias": None,
                "lineno_end": 1,
                "lineno_start": 1,
                "name": "datetime",
                "node_type": "import",
            },
            {
                "imports": [
                    {
                        "alias": None,
                        "lineno_end": 2,
                        "lineno_start": 2,
                        "name": "dataclass",
                        "node_type": "import",
                    }
                ],
                "lineno_end": 2,
                "lineno_start": 2,
                "module": "dataclasses",
                "node_type": "from_import",
            },
            {
                "imports": [
                    {
                        "alias": None,
                        "lineno_end": 3,
                        "lineno_start": 3,
                        "name": "Enum",
                        "node_type": "import",
                    }
                ],
                "lineno_end": 3,
                "lineno_start": 3,
                "module": "enum",
                "node_type": "from_import",
            },
            {
                "imports": [
                    {
                        "alias": None,
                        "lineno_end": 4,
                        "lineno_start": 4,
                        "name": "Any",
                        "node_type": "import",
                    },
                    {
                        "alias": None,
                        "lineno_end": 4,
                        "lineno_start": 4,
                        "name": "Union",
                        "node_type": "import",
                    },
                ],
                "lineno_end": 4,
                "lineno_start": 4,
                "module": "typing",
                "node_type": "from_import",
            },
            {
                "attrs": [
                    {
                        "default": "article",
                        "lineno_end": 8,
                        "lineno_start": 8,
                        "name": "article",
                        "node_type": "variable",
                        "properties": {},
                        "type_annotation": "str",
                    },
                    {
                        "default": "video",
                        "lineno_end": 9,
                        "lineno_start": 9,
                        "name": "video",
                        "node_type": "variable",
                        "properties": {},
                        "type_annotation": "str",
                    },
                ],
                "lineno_end": 9,
                "lineno_start": 7,
                "name": "MaterialType",
                "node_type": "class",
                "parents": ["str", "Enum"],
            },
            {
                "attrs": [
                    {
                        "default": None,
                        "lineno_end": 14,
                        "lineno_start": 14,
                        "name": "id",
                        "node_type": "variable",
                        "properties": {},
                        "type_annotation": "int",
                    },
                    {
                        "default": None,
                        "lineno_end": 15,
                        "lineno_start": 15,
                        "name": "description",
                        "node_type": "variable",
                        "properties": {},
                        "type_annotation": "str",
                    },
                    {
                        "default": None,
                        "lineno_end": 16,
                        "lineno_start": 16,
                        "name": "additional_properties",
                        "node_type": "variable",
                        "properties": {},
                        "type_annotation": {"Union": ["dict", "list", "tuple", "Any"]},
                    },
                    {
                        "default": {
                            "args": [],
                            "func_name": "datetime.datetime.now",
                            "kwargs": {},
                            "lineno_end": 17,
                            "lineno_start": 17,
                            "node_type": "func_call",
                        },
                        "lineno_end": 17,
                        "lineno_start": 17,
                        "name": "created_at",
                        "node_type": "variable",
                        "properties": {},
                        "type_annotation": "datetime.datetime",
                    },
                    {
                        "default": None,
                        "lineno_end": 18,
                        "lineno_start": 18,
                        "name": "updated_at",
                        "node_type": "variable",
                        "properties": {},
                        "type_annotation": "datetime.datetime",
                    },
                ],
                "lineno_end": 18,
                "lineno_start": 13,
                "name": "Material",
                "node_type": "class",
                "parents": [],
            },
            {
                "attrs": [
                    {
                        "default": None,
                        "lineno_end": 23,
                        "lineno_start": 23,
                        "name": "id",
                        "node_type": "variable",
                        "properties": {},
                        "type_annotation": "int",
                    },
                    {
                        "default": None,
                        "lineno_end": 24,
                        "lineno_start": 24,
                        "name": "description",
                        "node_type": "variable",
                        "properties": {},
                        "type_annotation": "str",
                    },
                    {
                        "default": None,
                        "lineno_end": 25,
                        "lineno_start": 25,
                        "name": "additional_properties",
                        "node_type": "variable",
                        "properties": {},
                        "type_annotation": {"Union": ["dict", "list"]},
                    },
                    {
                        "default": {
                            "args": [],
                            "func_name": "datetime.datetime.now",
                            "kwargs": {},
                            "lineno_end": 26,
                            "lineno_start": 26,
                            "node_type": "func_call",
                        },
                        "lineno_end": 26,
                        "lineno_start": 26,
                        "name": "created_at",
                        "node_type": "variable",
                        "properties": {},
                        "type_annotation": "datetime.datetime",
                    },
                    {
                        "default": None,
                        "lineno_end": 27,
                        "lineno_start": 27,
                        "name": "updated_at",
                        "node_type": "variable",
                        "properties": {},
                        "type_annotation": "datetime.datetime",
                    },
                ],
                "lineno_end": 27,
                "lineno_start": 22,
                "name": "Material2",
                "node_type": "class",
                "parents": [],
            },
        ],
    ),
    (
        test_data / "django_.py",
        [
            {
                "imports": [
                    {
                        "alias": None,
                        "lineno_end": 1,
                        "lineno_start": 1,
                        "name": "models",
                        "node_type": "import",
                    }
                ],
                "lineno_end": 1,
                "lineno_start": 1,
                "module": "django.db",
                "node_type": "from_import",
            },
            {
                "attrs": [
                    {
                        "default": {
                            "args": [],
                            "func_name": "models.CharField",
                            "kwargs": {"max_length": 50},
                            "lineno_end": 5,
                            "lineno_start": 5,
                            "node_type": "func_call",
                        },
                        "lineno_end": 5,
                        "lineno_start": 5,
                        "name": "first_name",
                        "node_type": "variable",
                        "properties": {},
                        "type_annotation": None,
                    },
                    {
                        "default": {
                            "args": [],
                            "func_name": "models.CharField",
                            "kwargs": {"max_length": 50},
                            "lineno_end": 6,
                            "lineno_start": 6,
                            "node_type": "func_call",
                        },
                        "lineno_end": 6,
                        "lineno_start": 6,
                        "name": "last_name",
                        "node_type": "variable",
                        "properties": {},
                        "type_annotation": None,
                    },
                    {
                        "default": {
                            "args": [],
                            "func_name": "models.CharField",
                            "kwargs": {"max_length": 100},
                            "lineno_end": 7,
                            "lineno_start": 7,
                            "node_type": "func_call",
                        },
                        "lineno_end": 7,
                        "lineno_start": 7,
                        "name": "instrument",
                        "node_type": "variable",
                        "properties": {},
                        "type_annotation": None,
                    },
                ],
                "lineno_end": 7,
                "lineno_start": 4,
                "name": "Musician",
                "node_type": "class",
                "parents": ["models.Model"],
            },
            {
                "attrs": [
                    {
                        "default": {
                            "args": ["Musician"],
                            "func_name": "models.ForeignKey",
                            "kwargs": {"on_delete": "models"},
                            "lineno_end": 11,
                            "lineno_start": 11,
                            "node_type": "func_call",
                        },
                        "lineno_end": 11,
                        "lineno_start": 11,
                        "name": "artist",
                        "node_type": "variable",
                        "properties": {},
                        "type_annotation": None,
                    },
                    {
                        "default": {
                            "args": [],
                            "func_name": "models.CharField",
                            "kwargs": {"max_length": 100},
                            "lineno_end": 12,
                            "lineno_start": 12,
                            "node_type": "func_call",
                        },
                        "lineno_end": 12,
                        "lineno_start": 12,
                        "name": "name",
                        "node_type": "variable",
                        "properties": {},
                        "type_annotation": None,
                    },
                    {
                        "default": {
                            "args": [],
                            "func_name": "models.DateField",
                            "kwargs": {},
                            "lineno_end": 13,
                            "lineno_start": 13,
                            "node_type": "func_call",
                        },
                        "lineno_end": 13,
                        "lineno_start": 13,
                        "name": "release_date",
                        "node_type": "variable",
                        "properties": {},
                        "type_annotation": None,
                    },
                    {
                        "default": {
                            "args": [],
                            "func_name": "models.IntegerField",
                            "kwargs": {},
                            "lineno_end": 14,
                            "lineno_start": 14,
                            "node_type": "func_call",
                        },
                        "lineno_end": 14,
                        "lineno_start": 14,
                        "name": "num_stars",
                        "node_type": "variable",
                        "properties": {},
                        "type_annotation": None,
                    },
                ],
                "lineno_end": 14,
                "lineno_start": 10,
                "name": "Album",
                "node_type": "class",
                "parents": ["models.Model"],
            },
            {
                "attrs": [],
                "lineno_end": 19,
                "lineno_start": 17,
                "name": "Topping",
                "node_type": "class",
                "parents": ["models.Model"],
            },
            {
                "attrs": [
                    {
                        "default": {
                            "args": ["Topping"],
                            "func_name": "models.ManyToManyField",
                            "kwargs": {},
                            "lineno_end": 24,
                            "lineno_start": 24,
                            "node_type": "func_call",
                        },
                        "lineno_end": 24,
                        "lineno_start": 24,
                        "name": "toppings",
                        "node_type": "variable",
                        "properties": {},
                        "type_annotation": None,
                    }
                ],
                "lineno_end": 24,
                "lineno_start": 22,
                "name": "Pizza",
                "node_type": "class",
                "parents": ["models.Model"],
            },
            {
                "attrs": [
                    {
                        "default": {
                            "args": [],
                            "func_name": "models.CharField",
                            "kwargs": {"max_length": 128},
                            "lineno_end": 28,
                            "lineno_start": 28,
                            "node_type": "func_call",
                        },
                        "lineno_end": 28,
                        "lineno_start": 28,
                        "name": "name",
                        "node_type": "variable",
                        "properties": {},
                        "type_annotation": None,
                    }
                ],
                "lineno_end": 31,
                "lineno_start": 27,
                "name": "Person",
                "node_type": "class",
                "parents": ["models.Model"],
            },
            {
                "attrs": [
                    {
                        "default": {
                            "args": [],
                            "func_name": "models.CharField",
                            "kwargs": {"max_length": 128},
                            "lineno_end": 35,
                            "lineno_start": 35,
                            "node_type": "func_call",
                        },
                        "lineno_end": 35,
                        "lineno_start": 35,
                        "name": "name",
                        "node_type": "variable",
                        "properties": {},
                        "type_annotation": None,
                    },
                    {
                        "default": {
                            "args": ["Person"],
                            "func_name": "models.ManyToManyField",
                            "kwargs": {"through": "Membership"},
                            "lineno_end": 36,
                            "lineno_start": 36,
                            "node_type": "func_call",
                        },
                        "lineno_end": 36,
                        "lineno_start": 36,
                        "name": "members",
                        "node_type": "variable",
                        "properties": {},
                        "type_annotation": None,
                    },
                ],
                "lineno_end": 39,
                "lineno_start": 34,
                "name": "Group",
                "node_type": "class",
                "parents": ["models.Model"],
            },
            {
                "attrs": [
                    {
                        "default": {
                            "args": ["Person"],
                            "func_name": "models.ForeignKey",
                            "kwargs": {"on_delete": "models"},
                            "lineno_end": 43,
                            "lineno_start": 43,
                            "node_type": "func_call",
                        },
                        "lineno_end": 43,
                        "lineno_start": 43,
                        "name": "person",
                        "node_type": "variable",
                        "properties": {},
                        "type_annotation": None,
                    },
                    {
                        "default": {
                            "args": ["Group"],
                            "func_name": "models.ForeignKey",
                            "kwargs": {"on_delete": "models"},
                            "lineno_end": 44,
                            "lineno_start": 44,
                            "node_type": "func_call",
                        },
                        "lineno_end": 44,
                        "lineno_start": 44,
                        "name": "group",
                        "node_type": "variable",
                        "properties": {},
                        "type_annotation": None,
                    },
                    {
                        "default": {
                            "args": [],
                            "func_name": "models.DateField",
                            "kwargs": {},
                            "lineno_end": 45,
                            "lineno_start": 45,
                            "node_type": "func_call",
                        },
                        "lineno_end": 45,
                        "lineno_start": 45,
                        "name": "date_joined",
                        "node_type": "variable",
                        "properties": {},
                        "type_annotation": None,
                    },
                    {
                        "default": {
                            "args": [],
                            "func_name": "models.CharField",
                            "kwargs": {"max_length": 64},
                            "lineno_end": 46,
                            "lineno_start": 46,
                            "node_type": "func_call",
                        },
                        "lineno_end": 46,
                        "lineno_start": 46,
                        "name": "invite_reason",
                        "node_type": "variable",
                        "properties": {},
                        "type_annotation": None,
                    },
                ],
                "lineno_end": 46,
                "lineno_start": 42,
                "name": "Membership",
                "node_type": "class",
                "parents": ["models.Model"],
            },
            {
                "attrs": [
                    {
                        "default": {
                            "args": [],
                            "func_name": "models.IntegerField",
                            "kwargs": {},
                            "lineno_end": 50,
                            "lineno_start": 50,
                            "node_type": "func_call",
                        },
                        "lineno_end": 50,
                        "lineno_start": 50,
                        "name": "horn_length",
                        "node_type": "variable",
                        "properties": {},
                        "type_annotation": None,
                    }
                ],
                "lineno_end": 54,
                "lineno_start": 49,
                "name": "Ox",
                "node_type": "class",
                "parents": ["models.Model"],
            },
            {
                "attrs": [
                    {
                        "default": {
                            "args": [],
                            "func_name": "models.CharField",
                            "kwargs": {"max_length": 30},
                            "lineno_end": 58,
                            "lineno_start": 58,
                            "node_type": "func_call",
                        },
                        "lineno_end": 58,
                        "lineno_start": 58,
                        "name": "title",
                        "node_type": "variable",
                        "properties": {},
                        "type_annotation": None,
                    }
                ],
                "lineno_end": 64,
                "lineno_start": 57,
                "name": "Publication",
                "node_type": "class",
                "parents": ["models.Model"],
            },
            {
                "attrs": [
                    {
                        "default": {
                            "args": [],
                            "func_name": "models.CharField",
                            "kwargs": {"max_length": 100},
                            "lineno_end": 68,
                            "lineno_start": 68,
                            "node_type": "func_call",
                        },
                        "lineno_end": 68,
                        "lineno_start": 68,
                        "name": "headline",
                        "node_type": "variable",
                        "properties": {},
                        "type_annotation": None,
                    },
                    {
                        "default": {
                            "args": ["Publication"],
                            "func_name": "models.ManyToManyField",
                            "kwargs": {},
                            "lineno_end": 69,
                            "lineno_start": 69,
                            "node_type": "func_call",
                        },
                        "lineno_end": 69,
                        "lineno_start": 69,
                        "name": "publications",
                        "node_type": "variable",
                        "properties": {},
                        "type_annotation": None,
                    },
                ],
                "lineno_end": 75,
                "lineno_start": 67,
                "name": "Article",
                "node_type": "class",
                "parents": ["models.Model"],
            },
        ],
    ),
    (
        test_data / "encode_orm_.py",
        [
            {
                "alias": None,
                "lineno_end": 1,
                "lineno_start": 1,
                "name": "databases",
                "node_type": "import",
            },
            {
                "alias": None,
                "lineno_end": 2,
                "lineno_start": 2,
                "name": "orm",
                "node_type": "import",
            },
            {
                "alias": None,
                "lineno_end": 3,
                "lineno_start": 3,
                "name": "sqlalchemy",
                "node_type": "import",
            },
            {
                "default": {
                    "args": ["sqlite:///db.sqlite"],
                    "func_name": "databases.Database",
                    "kwargs": {},
                    "lineno_end": 5,
                    "lineno_start": 5,
                    "node_type": "func_call",
                },
                "lineno_end": 5,
                "lineno_start": 5,
                "name": "database",
                "node_type": "variable",
                "properties": {},
                "type_annotation": None,
            },
            {
                "default": {
                    "args": [],
                    "func_name": "sqlalchemy.MetaData",
                    "kwargs": {},
                    "lineno_end": 6,
                    "lineno_start": 6,
                    "node_type": "func_call",
                },
                "lineno_end": 6,
                "lineno_start": 6,
                "name": "metadata",
                "node_type": "variable",
                "properties": {},
                "type_annotation": None,
            },
            {
                "attrs": [
                    {
                        "default": "notes",
                        "lineno_end": 10,
                        "lineno_start": 10,
                        "name": "__tablename__",
                        "node_type": "variable",
                        "properties": {},
                        "type_annotation": "str",
                    },
                    {
                        "default": "database",
                        "lineno_end": 11,
                        "lineno_start": 11,
                        "name": "__database__",
                        "node_type": "variable",
                        "properties": {},
                        "type_annotation": None,
                    },
                    {
                        "default": "metadata",
                        "lineno_end": 12,
                        "lineno_start": 12,
                        "name": "__metadata__",
                        "node_type": "variable",
                        "properties": {},
                        "type_annotation": None,
                    },
                    {
                        "default": {
                            "args": [],
                            "func_name": "orm.Integer",
                            "kwargs": {"primary_key": True},
                            "lineno_end": 14,
                            "lineno_start": 14,
                            "node_type": "func_call",
                        },
                        "lineno_end": 14,
                        "lineno_start": 14,
                        "name": "id",
                        "node_type": "variable",
                        "properties": {},
                        "type_annotation": None,
                    },
                    {
                        "default": {
                            "args": [],
                            "func_name": "orm.String",
                            "kwargs": {"index": True, "max_length": 100},
                            "lineno_end": 15,
                            "lineno_start": 15,
                            "node_type": "func_call",
                        },
                        "lineno_end": 15,
                        "lineno_start": 15,
                        "name": "text",
                        "node_type": "variable",
                        "properties": {},
                        "type_annotation": None,
                    },
                    {
                        "default": {
                            "args": [],
                            "func_name": "orm.Boolean",
                            "kwargs": {"default": False},
                            "lineno_end": 16,
                            "lineno_start": 16,
                            "node_type": "func_call",
                        },
                        "lineno_end": 16,
                        "lineno_start": 16,
                        "name": "completed",
                        "node_type": "variable",
                        "properties": {},
                        "type_annotation": None,
                    },
                ],
                "lineno_end": 16,
                "lineno_start": 9,
                "name": "Note",
                "node_type": "class",
                "parents": ["orm.Model"],
            },
            {
                "attrs": [
                    {
                        "default": "album",
                        "lineno_end": 20,
                        "lineno_start": 20,
                        "name": "__tablename__",
                        "node_type": "variable",
                        "properties": {},
                        "type_annotation": "str",
                    },
                    {
                        "default": "metadata",
                        "lineno_end": 21,
                        "lineno_start": 21,
                        "name": "__metadata__",
                        "node_type": "variable",
                        "properties": {},
                        "type_annotation": None,
                    },
                    {
                        "default": "database",
                        "lineno_end": 22,
                        "lineno_start": 22,
                        "name": "__database__",
                        "node_type": "variable",
                        "properties": {},
                        "type_annotation": None,
                    },
                    {
                        "default": {
                            "args": [],
                            "func_name": "orm.Integer",
                            "kwargs": {"primary_key": True},
                            "lineno_end": 24,
                            "lineno_start": 24,
                            "node_type": "func_call",
                        },
                        "lineno_end": 24,
                        "lineno_start": 24,
                        "name": "id",
                        "node_type": "variable",
                        "properties": {},
                        "type_annotation": None,
                    },
                    {
                        "default": {
                            "args": [],
                            "func_name": "orm.String",
                            "kwargs": {"max_length": 100},
                            "lineno_end": 25,
                            "lineno_start": 25,
                            "node_type": "func_call",
                        },
                        "lineno_end": 25,
                        "lineno_start": 25,
                        "name": "name",
                        "node_type": "variable",
                        "properties": {},
                        "type_annotation": None,
                    },
                ],
                "lineno_end": 25,
                "lineno_start": 19,
                "name": "Album",
                "node_type": "class",
                "parents": ["orm.Model"],
            },
            {
                "attrs": [
                    {
                        "default": "track",
                        "lineno_end": 29,
                        "lineno_start": 29,
                        "name": "__tablename__",
                        "node_type": "variable",
                        "properties": {},
                        "type_annotation": "str",
                    },
                    {
                        "default": "metadata",
                        "lineno_end": 30,
                        "lineno_start": 30,
                        "name": "__metadata__",
                        "node_type": "variable",
                        "properties": {},
                        "type_annotation": None,
                    },
                    {
                        "default": "database",
                        "lineno_end": 31,
                        "lineno_start": 31,
                        "name": "__database__",
                        "node_type": "variable",
                        "properties": {},
                        "type_annotation": None,
                    },
                    {
                        "default": {
                            "args": [],
                            "func_name": "orm.Integer",
                            "kwargs": {"primary_key": True},
                            "lineno_end": 33,
                            "lineno_start": 33,
                            "node_type": "func_call",
                        },
                        "lineno_end": 33,
                        "lineno_start": 33,
                        "name": "id",
                        "node_type": "variable",
                        "properties": {},
                        "type_annotation": None,
                    },
                    {
                        "default": {
                            "args": ["Album"],
                            "func_name": "orm.ForeignKey",
                            "kwargs": {},
                            "lineno_end": 34,
                            "lineno_start": 34,
                            "node_type": "func_call",
                        },
                        "lineno_end": 34,
                        "lineno_start": 34,
                        "name": "album",
                        "node_type": "variable",
                        "properties": {},
                        "type_annotation": None,
                    },
                    {
                        "default": {
                            "args": [],
                            "func_name": "orm.String",
                            "kwargs": {"max_length": 100},
                            "lineno_end": 35,
                            "lineno_start": 35,
                            "node_type": "func_call",
                        },
                        "lineno_end": 35,
                        "lineno_start": 35,
                        "name": "title",
                        "node_type": "variable",
                        "properties": {},
                        "type_annotation": None,
                    },
                    {
                        "default": {
                            "args": [],
                            "func_name": "orm.Integer",
                            "kwargs": {},
                            "lineno_end": 36,
                            "lineno_start": 36,
                            "node_type": "func_call",
                        },
                        "lineno_end": 36,
                        "lineno_start": 36,
                        "name": "position",
                        "node_type": "variable",
                        "properties": {},
                        "type_annotation": None,
                    },
                ],
                "lineno_end": 36,
                "lineno_start": 28,
                "name": "Track",
                "node_type": "class",
                "parents": ["orm.Model"],
            },
            {
                "attrs": [
                    {
                        "default": "org",
                        "lineno_end": 40,
                        "lineno_start": 40,
                        "name": "__tablename__",
                        "node_type": "variable",
                        "properties": {},
                        "type_annotation": "str",
                    },
                    {
                        "default": "metadata",
                        "lineno_end": 41,
                        "lineno_start": 41,
                        "name": "__metadata__",
                        "node_type": "variable",
                        "properties": {},
                        "type_annotation": None,
                    },
                    {
                        "default": "database",
                        "lineno_end": 42,
                        "lineno_start": 42,
                        "name": "__database__",
                        "node_type": "variable",
                        "properties": {},
                        "type_annotation": None,
                    },
                    {
                        "default": {
                            "args": [],
                            "func_name": "orm.Integer",
                            "kwargs": {"primary_key": True},
                            "lineno_end": 44,
                            "lineno_start": 44,
                            "node_type": "func_call",
                        },
                        "lineno_end": 44,
                        "lineno_start": 44,
                        "name": "id",
                        "node_type": "variable",
                        "properties": {},
                        "type_annotation": None,
                    },
                    {
                        "default": {
                            "args": [],
                            "func_name": "orm.String",
                            "kwargs": {"max_length": 100},
                            "lineno_end": 45,
                            "lineno_start": 45,
                            "node_type": "func_call",
                        },
                        "lineno_end": 45,
                        "lineno_start": 45,
                        "name": "ident",
                        "node_type": "variable",
                        "properties": {},
                        "type_annotation": None,
                    },
                ],
                "lineno_end": 45,
                "lineno_start": 39,
                "name": "Organisation",
                "node_type": "class",
                "parents": ["orm.Model"],
            },
            {
                "attrs": [
                    {
                        "default": "team",
                        "lineno_end": 49,
                        "lineno_start": 49,
                        "name": "__tablename__",
                        "node_type": "variable",
                        "properties": {},
                        "type_annotation": "str",
                    },
                    {
                        "default": "metadata",
                        "lineno_end": 50,
                        "lineno_start": 50,
                        "name": "__metadata__",
                        "node_type": "variable",
                        "properties": {},
                        "type_annotation": None,
                    },
                    {
                        "default": "database",
                        "lineno_end": 51,
                        "lineno_start": 51,
                        "name": "__database__",
                        "node_type": "variable",
                        "properties": {},
                        "type_annotation": None,
                    },
                    {
                        "default": {
                            "args": [],
                            "func_name": "orm.Integer",
                            "kwargs": {"primary_key": True},
                            "lineno_end": 53,
                            "lineno_start": 53,
                            "node_type": "func_call",
                        },
                        "lineno_end": 53,
                        "lineno_start": 53,
                        "name": "id",
                        "node_type": "variable",
                        "properties": {},
                        "type_annotation": None,
                    },
                    {
                        "default": {
                            "args": ["Organisation"],
                            "func_name": "orm.ForeignKey",
                            "kwargs": {},
                            "lineno_end": 54,
                            "lineno_start": 54,
                            "node_type": "func_call",
                        },
                        "lineno_end": 54,
                        "lineno_start": 54,
                        "name": "org",
                        "node_type": "variable",
                        "properties": {},
                        "type_annotation": None,
                    },
                    {
                        "default": {
                            "args": [],
                            "func_name": "orm.String",
                            "kwargs": {"max_length": 100},
                            "lineno_end": 55,
                            "lineno_start": 55,
                            "node_type": "func_call",
                        },
                        "lineno_end": 55,
                        "lineno_start": 55,
                        "name": "name",
                        "node_type": "variable",
                        "properties": {},
                        "type_annotation": None,
                    },
                ],
                "lineno_end": 55,
                "lineno_start": 48,
                "name": "Team",
                "node_type": "class",
                "parents": ["orm.Model"],
            },
            {
                "attrs": [
                    {
                        "default": "member",
                        "lineno_end": 59,
                        "lineno_start": 59,
                        "name": "__tablename__",
                        "node_type": "variable",
                        "properties": {},
                        "type_annotation": "str",
                    },
                    {
                        "default": "metadata",
                        "lineno_end": 60,
                        "lineno_start": 60,
                        "name": "__metadata__",
                        "node_type": "variable",
                        "properties": {},
                        "type_annotation": None,
                    },
                    {
                        "default": "database",
                        "lineno_end": 61,
                        "lineno_start": 61,
                        "name": "__database__",
                        "node_type": "variable",
                        "properties": {},
                        "type_annotation": None,
                    },
                    {
                        "default": {
                            "args": [],
                            "func_name": "orm.Integer",
                            "kwargs": {"primary_key": True},
                            "lineno_end": 63,
                            "lineno_start": 63,
                            "node_type": "func_call",
                        },
                        "lineno_end": 63,
                        "lineno_start": 63,
                        "name": "id",
                        "node_type": "variable",
                        "properties": {},
                        "type_annotation": None,
                    },
                    {
                        "default": {
                            "args": ["Team"],
                            "func_name": "orm.ForeignKey",
                            "kwargs": {},
                            "lineno_end": 64,
                            "lineno_start": 64,
                            "node_type": "func_call",
                        },
                        "lineno_end": 64,
                        "lineno_start": 64,
                        "name": "team",
                        "node_type": "variable",
                        "properties": {},
                        "type_annotation": None,
                    },
                    {
                        "default": {
                            "args": [],
                            "func_name": "orm.String",
                            "kwargs": {"max_length": 100},
                            "lineno_end": 65,
                            "lineno_start": 65,
                            "node_type": "func_call",
                        },
                        "lineno_end": 65,
                        "lineno_start": 65,
                        "name": "email",
                        "node_type": "variable",
                        "properties": {},
                        "type_annotation": None,
                    },
                ],
                "lineno_end": 65,
                "lineno_start": 58,
                "name": "Member",
                "node_type": "class",
                "parents": ["orm.Model"],
            },
        ],
    ),
    (
        test_data / "pydal_.py",
        [
            {
                "imports": [
                    {
                        "alias": None,
                        "lineno_end": 3,
                        "lineno_start": 3,
                        "name": "DAL",
                        "node_type": "import",
                    },
                    {
                        "alias": None,
                        "lineno_end": 3,
                        "lineno_start": 3,
                        "name": "Field",
                        "node_type": "import",
                    },
                ],
                "lineno_end": 3,
                "lineno_start": 3,
                "module": "pydal",
                "node_type": "from_import",
            },
            {
                "default": {
                    "args": ["sqlite://test.db"],
                    "func_name": "DAL",
                    "kwargs": {"folder": "dbs"},
                    "lineno_end": 5,
                    "lineno_start": 5,
                    "node_type": "func_call",
                },
                "lineno_end": 5,
                "lineno_start": 5,
                "name": "db",
                "node_type": "variable",
                "properties": {},
                "type_annotation": None,
            },
            {
                "args": [
                    "cars",
                    {
                        "args": ["name"],
                        "func_name": "Field",
                        "kwargs": {},
                        "lineno_end": 7,
                        "lineno_start": 7,
                        "node_type": "func_call",
                    },
                    {
                        "args": ["price"],
                        "func_name": "Field",
                        "kwargs": {"type": "integer"},
                        "lineno_end": 7,
                        "lineno_start": 7,
                        "node_type": "func_call",
                    },
                ],
                "func_name": "db.define_table",
                "kwargs": {},
                "lineno_end": 7,
                "lineno_start": 7,
                "node_type": "func_call",
            },
            {
                "args": [],
                "func_name": "db.cars.insert",
                "kwargs": {"name": "Audi", "price": 52642},
                "lineno_end": 8,
                "lineno_start": 8,
                "node_type": "func_call",
            },
            {
                "args": [],
                "func_name": "db.cars.insert",
                "kwargs": {"name": "Skoda", "price": 9000},
                "lineno_end": 10,
                "lineno_start": 10,
                "node_type": "func_call",
            },
            {
                "args": [],
                "func_name": "db.cars.insert",
                "kwargs": {"name": "Volvo", "price": 29000},
                "lineno_end": 11,
                "lineno_start": 11,
                "node_type": "func_call",
            },
            {
                "args": [],
                "func_name": "db.cars.insert",
                "kwargs": {"name": "Bentley", "price": 350000},
                "lineno_end": 12,
                "lineno_start": 12,
                "node_type": "func_call",
            },
            {
                "args": [],
                "func_name": "db.cars.insert",
                "kwargs": {"name": "Citroen", "price": 21000},
                "lineno_end": 13,
                "lineno_start": 13,
                "node_type": "func_call",
            },
            {
                "args": [],
                "func_name": "db.cars.insert",
                "kwargs": {"name": "Hummer", "price": 41400},
                "lineno_end": 14,
                "lineno_start": 14,
                "node_type": "func_call",
            },
            {
                "args": [],
                "func_name": "db.cars.insert",
                "kwargs": {"name": "Volkswagen", "price": 21600},
                "lineno_end": 15,
                "lineno_start": 15,
                "node_type": "func_call",
            },
            {
                "args": [],
                "func_name": "db.close",
                "kwargs": {},
                "lineno_end": 19,
                "lineno_start": 19,
                "node_type": "func_call",
            },
            {
                "args": ["i"],
                "func_name": "print",
                "kwargs": {},
                "lineno_end": 22,
                "lineno_start": 22,
                "node_type": "func_call",
            },
        ],
    ),
]


@pytest.mark.parametrize("file_path,result", params)
def test_parse_from_file(file_path: str, result: dict):
    print([x.json() for x in parse_from_file(file_path=file_path)])
    assert [x.dict() for x in parse_from_file(file_path=file_path)] == result
